name: flutter_date_time_label
description: A package for displaying date/time with different styles.
version: 0.0.5
repository: https://github.com/LarryHsiao/flutter_date_time_label

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:

