name: flutter_date_time_label
description: A package for displaying date/time with different styles for quick implementation.
version: 0.0.9
repository: https://github.com/LarryHsiao/flutter_date_time_label

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

