name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:  
    - uses: jddeep/Flutter-Runner@1.2.0
    - name: clean stale build and cache
      uses: ./action
      with:
        args: clean
    - name: install dependencies
      uses: ./action
      with:
        args: pub get

    - name: Verify formatting
      uses: ./action
      with: 
        args: format --output=none --set-exit-if-changed .

    - name: Analyze project source
      uses: ./action
      with: 
        args: analyze --fatal-infos

    - name: Run tests
      uses: ./action
      with: 
        args: analyze --fatal-infos
